### ISSUE TITLE
latin names

### ISSUE THREAD

**Issue by v-prt** [v-prt/plantgeek#49]

**Comment by oliversalzburg** [comment]
Hi @v-prt, I just discovered your project today and I absolutely love it. I couldn't find a more direct way to contact you, so I figured I'd take this issue as an opportunity to get in touch.

I have recently started to work on my own (free and open) plant care software project and would very much like to incorporate some of your collected data into it. Naturally, your project would be attributed and linked to at every location where the data is utilized.

I don't want to come completely empty-handed in asking for this. I would gladly help out in collecting latin/scientific names for as many plants in your DB as possible. I also noticed that the primary name sometimes already includes the scientific one, sometimes it's in the secondary name. I'm not sure if you would want any of the existing labeling to change or if this should purely be an additional field.

Either way, please let me know your thoughts about this. Cheers :)

**Comment by v-prt** [comment]
Hi @oliversalzburg! Thanks for reaching out 😊

This was actually a class project and I got most of my data from another site (a plant shop), which is why sometimes the naming convention isn't consistent. You can see the source links on the plant profiles. I'm still interested in collaborating if you are, as I would like to collect more data and clean up some of the info I already have. I would like the primary names to be the latin/scientific and the secondary to be the "common" name (for example, primary would be "Monstera deliciosa" and secondary would be "Swiss cheese plant").

If you'd like to discuss this further, you may email me at v-peart@outlook.com 😊
